name: Release

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  release:
    name: Release / Node ${{ matrix.node }}
    strategy:
      matrix:
        node: ['18']

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - run: |
          npm ci
          npm run build
          
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "exports.createClient = createClient;"
          replace: "module.exports = createClient;"
          include: "**index.js"
          
      - name: Create a release
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
