name: Release

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  release:
    name: Release / Node ${{ matrix.node }}
    strategy:
      matrix:
        node: ['18']

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          registry-url: https://registry.npmjs.org
      - run: |
          npm ci
          npm run build
      - run: npm publish --public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
